# Generated by Django 5.2.8 on 2025-11-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
    ]
