# Generated by Django 5.2.8 on 2025-11-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
